import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const clashDisplay = localFont({
  src: [
    {
      path: '../public/fonts/ClashDisplay-Regular.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/ClashDisplay-Bold.woff2',
      weight: '700',
      style: 'bold',
    },
    {
      path: '../public/fonts/ClashDisplay-Extralight.woff2',
      weight: '200',
      style: 'extralight',
    },
    {
      path: '../public/fonts/ClashDisplay-Light.woff',
      weight: '300',
      style: 'light',
    },
    {
      path: '../public/fonts/ClashDisplay-Medium.woff',
      weight: '500',
      style: 'medium',
    },
    {
      path: '../public/fonts/ClashDisplay-Semibold.woff',
      weight: '600',
      style: 'semibold',
    },
  ],
  variable: "--font-clash-display",
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={clashDisplay.className}>{children}</body>
    </html>
  )
}
