import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const clashDisplay = localFont({
  src: [
    {
      path: 'fonts/ClashDisplay-Regular.woff',
      weight: '400',
      style: 'normal',
    },
    // {
    //   path: 'fonts/ClashDisplay-Bold.woff2',
    //   weight: '700',
    //   style: 'bold',
    // },
    // {
    //   path: 'fonts/ClashDisplay-Extralight.woff2',
    //   weight: '200',
    //   style: 'extralight',
    // },
    // {
    //   path: './fonts/ClashDisplay-Light.woff2',
    //   weight: '300',
    //   style: 'light',
    // },
    // {
    //   path: './fonts/ClashDisplay-Medium.woff2',
    //   weight: '500',
    //   style: 'medium',
    // },
    // {
    //   path: './fonts/ClashDisplay-Semibold.woff2',
    //   weight: '600',
    //   style: 'semibold',
    // },
  ],
  variable: "--font-clash-bold",
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`${clashDisplay.variable}`}>{children}</body>
    </html>
  )
}
